package de.coulees.B1progame.musicxcst.config;

import java.util.ArrayList;
import java.util.List;

public final class CstMusicConfig {
    public long maxFileSizeBytes = 25L * 1024L * 1024L;
    public long maxStoragePerPlayerBytes = 250L * 1024L * 1024L;
    public long maxTotalServerStorageBytes = 2L * 1024L * 1024L * 1024L;
    public List<String> allowedFileExtensions = new ArrayList<>(List.of("mp3", "mp4", "wav", "ogg", "flac", "m4a", "aac", "webm", "avi"));
    public String serverImportFolder = "music-import";
    public String serverNormalizedAudioFolder = "music-normalized";
    public String normalizedOutputFormat = "ogg";
    public String ffmpegMode = "system";
    public int audioBitrateKbps = 128;
    public int maxUploadMb = 25;
    public int maxDurationSeconds = 0;
    public boolean maxMusicDurationEnabled = true;
    public int maxMusicDurationSeconds = 600;
    public String maxMusicDurationExamples = "150 seconds = 2:30, 600 seconds = 10:00, 3600 seconds = 1:00:00. Set maxMusicDurationEnabled=false for no limit.";
    public boolean maxMusicFilesPerPlayerEnabled = false;
    public int maxMusicFilesPerPlayer = 10;
    public String playerLimitMode = "confirm_delete_oldest";
    public String playerLimitModeExamples = "confirm_delete_oldest, auto_delete_oldest, block_new_upload";
    public int maxServerStorageMb = 2048;
    public boolean allowServerSideTranscoding = false;
    public String audioBitrate = "128k";
    public int sampleRate = 44100;
    public int previewCacheSeconds = 15;
    public int clientUploadBytesPerSecond = 256 * 1024;
    public boolean stereoEnabled = true;
    public boolean monoDownmix = false;
    public String ffmpegPath = "ffmpeg";
    public boolean ffmpegManagedDownloadAllowed = false;
    public String ffmpegManagedSourceUrl = "";
    public String ffmpegManagedVersion = "";
    public String ffmpegManagedSha256 = "";
    public String ffmpegManagedLicense = "";
    public boolean clientFfmpegSetupAcknowledged = false;
    public int playbackRadiusBlocks = 96;
    public int rangeCheckIntervalTicks = 20;
    public int fadeInMilliseconds = 250;
    public int fadeOutMilliseconds = 500;
    public long clientCacheSizeBytes = 1024L * 1024L * 1024L;
    public String absoluteImportSubfolder = "imported";
    public boolean allowSingleplayerAbsolutePaths = true;
    public boolean allowAdminAbsoluteServerPaths = false;
    public boolean softDeleteEnabled = true;
    public boolean allowFoundDiscsPlayback = true;
    public boolean ownerOnlyPlayback = false;
    public boolean adminBypass = true;
    public boolean debugLogging = false;
}
