#!/usr/bin/env python3
"""Small, rate-limited helper for custom item rendering research.

The script fetches a few known/current documentation pages and stores copies
under tools/research_cache. It is intentionally not a crawler.
"""

from __future__ import annotations

import re
import time
import urllib.error
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / "tools" / "research_cache"
SUMMARY = ROOT / "tools" / "research_texture_rendering_summary.md"
URLS = [
    "https://docs.fabricmc.net/develop/rendering/basic-concepts",
    "https://docs.fabricmc.net/develop/items/first-item",
    "https://docs.fabricmc.net/develop/items/custom-item-groups",
    "https://modrinth.com/mod/fabric-api/version/0.150.0%2B26.1.2",
    "https://docs.neoforged.net/primer/docs/1.21.6/",
]


def slug(url: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", url).strip("_")[:96] + ".html"


def fetch(url: str) -> tuple[int | None, str]:
    request = urllib.request.Request(url, headers={"User-Agent": "musicxcst-texture-rendering-audit/1.0"})
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            data = response.read(512_000)
            return response.status, data.decode("utf-8", errors="replace")
    except urllib.error.URLError as exc:
        return None, f"FETCH FAILED: {exc}"


def main() -> None:
    CACHE.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Texture Rendering Research Summary",
        "",
        "This file is generated by `tools/research_rendering_docs.py`.",
        "",
        "## Sources",
    ]
    for index, url in enumerate(URLS):
        status, text = fetch(url)
        target = CACHE / slug(url)
        target.write_text(text, encoding="utf-8")
        lines.append(f"- {url} -> `{target.relative_to(ROOT)}` status `{status}`")
        if index != len(URLS) - 1:
            time.sleep(1.0)

    lines += [
        "",
        "## Findings",
        "",
        "- Fabric's current rendering docs for 26.1.2 describe the post-1.21.6 render-state pipeline and warn that direct/raw GL style rendering is not the stable path.",
        "- The repository already targets the new item render-state path by injecting after `ItemModelResolver.appendItemLayers` and appending an `ItemStackRenderState.LayerRenderState`.",
        "- The static `assets/musicxcst/items/blueprint_cd.json` plus `models/item/blueprint_cd.json` can only select a static model and support component tinting; that cannot represent arbitrary per-stack 16x16 pixels by itself.",
        "- The safest focused fix for this codebase is to keep the current render-state layer approach, make the appended layer behave like a real flat generated item layer, and verify via Gradle against the exact mapped 26.1.2 classes.",
        "- `BuiltinItemRendererRegistry` examples from older Fabric versions are not used here because Minecraft 26.1.2 uses the newer extracted item render-state system, and this repo already has mixins against that system.",
    ]
    SUMMARY.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {SUMMARY.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
